  <div class="manage-event"><p>manage events</p><div class="total"><p>Total Events:67</p></div></div>
            <div class="username"><p>user</p>
            <div class="styled-select fl width200">
                       <select>
                          <option>john</option>
                          <option>trent</option>
                          <option>frnak</option>
                       </select>
                  </div>
                  </div>
            <div class="clr"></div>
                  <table id="eventTbl" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0">
                  <thead>
  <tr>
    <th>Id</th>
    <th>Event Name</th>
    <th>Location</th>
    <th>Date</th>
    <th>Friends can post</th>
    <th>Friends can Share</th>
    <th>Public</th>
    <th>Viewable Form</th>
    <th>Viewable To</th>
    <th>Self Destruct</th>
    <th>Action</th>
   
  </tr>
  </thead>
   
    
              
<?php 
foreach ($paginator as $key => $row) {
    # code..
?>
    <tr>
    <td> <?php echo $key+1 ?></td>
    <td><?php echo $row -> name ?></td>
    <td><?php echo $row -> location ?></td>
    <td><?php echo $row -> date ?></td>
    <td><?php echo $row -> friends_can_post ?></td>
    <td><?php echo $row -> friends_can_share ?></td>
    <td><?php echo $row -> public ?></td>
    <td><?php echo $row ->viewable_from ?></td>
        <td><?php echo $row ->viewable_to ?></td>
                <td><?php echo $row ->self_destruct ?></td>

    
<td><a class="intab" href="/admin/event/add"><img src="/img/status.png"></a></td>
     <td><a class="intab" href="/admin/event/edit/<?php echo $row -> event_id ?>"><img src="/img/edit.png"></a></td>
    <td><a class="intab" href="/admin/event/view/<?php echo $row -> event_id ?>"><img src="/img/eye.png"></a></td>
  </tr>

    
   
   <?php  }?>
   </table>

   <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array()
);
?>
