 <?php 
                     $MemHelper = $this->Mem();

 ?> 
              <div class="accnt-left clearfix">
                <div class="top">

                  <strong>total  registered user: <span><?php echo $total ?></span></strong>
                  <div class="drk clearfix">
                      <div class="col-1">user registered in past day</div>
                      <div class="col-2"><?php echo $pastday ?></div>
                  </div>
                  <div class="blue clearfix">
                      <div class="col-1">user registered in past week</div>
                      <div class="col-2"><?php echo $pastweek ?></div>
                  </div>
                  <div class="drk clearfix">
                      <div class="col-1">user registered in past month</div>
                      <div class="col-2"><?php echo $pastmonth ?></div>
                  </div>
                  <div class="blue clearfix total">
                      <div class="col-1">total invites to date</div>
                      <div class="col-2">100,000</div>
                  </div>

                </div>

                  <div class="bottom">

                    <div class="drk clearfix">
                        <div class="col-1">plan usage</div>
                        <div class="col-2">#</div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-1">A (Description)</div>
                        <div class="col-2">10,000</div>
                    </div>
                    <div class="drk clearfix">
                        <div class="col-1">B (Description)</div>
                        <div class="col-2">100,000</div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-1">B (Description)</div>
                        <div class="col-2">100,000</div>
                    </div>

                  </div>

              </div>

              <div class="accnt-right">

                <div class="top">

                  <strong>total  data on S3: <span><?=$MemHelper->toByteString($s3Total->data_usage)?></span></strong>
                  <div class="drk clearfix">
                      <div class="col-6">total of images</div>
                      <div class="col-6">average image size</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-6"><?php echo $s3Total->total_image?></div>
                      <div class="col-6"><?php echo $MemHelper->toByteString($s3Total->average_image);?></div>
                  </div>

                  <div class="drk clearfix">
                      <div class="col-4">total # of video</div>
                      <div class="col-4">average video size</div>
                      <div class="col-4">average duration</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-4"><?php echo $s3Total->total_vedio?></div>
                      <div class="col-4"><?php echo $MemHelper->toByteString($s3Total->average_vedio);?></div>
                      <div class="col-4">10 minutes</div>
                  </div>

                  <div class="drk clearfix">
                      <div class="col-4">total # of audio</div>
                      <div class="col-4">average audio size</div>
                      <div class="col-4">average duration</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-4"><?php echo $s3Total->total_audio?></div>
                      <div class="col-4"><?php echo $MemHelper->toByteString($s3Total->average_audio)?></div>
                      <div class="col-4">10 seconds</div>
                  </div>

                  <div class="bottom">


                    <div class="drk clearfix">
                        <div class="col-3">invite sent</div>
                        <div class="col-3">date</div>
                        <div class="col-3"> week</div>
                        <div class="col-3">month</div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-3">feedback</div>
                        <div class="col-3">10</div>
                        <div class="col-3">100</div>
                        <div class="col-3">1,000</div>
                    </div>
                    <div class="drk clearfix">
                        <div class="col-3">twitter</div>
                        <div class="col-3">10</div>
                        <div class="col-3">100</div>
                        <div class="col-3">1,000</div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-3">email</div>
                        <div class="col-3">600</div>
                        <div class="col-3">600</div>
                        <div class="col-3">6,000</div>
                    </div>

                  </div>
                </div>

              </div>

 

    