 <?php 
                     $MemHelper = $this->Mem();

 ?> 
              <div class="accnt-left clearfix">
                <div class="top">

                  <strong>total  registered user: <span><?php echo $total ?></span></strong>
                  <div class="drk clearfix">
                      <div class="col-1">user registered in past day</div>
                      <div class="col-2"><?php echo $pastday ?></div>
                  </div>
                  <div class="blue clearfix">
                      <div class="col-1">user registered in past week</div>
                      <div class="col-2"><?php echo $pastweek ?></div>
                  </div>
                  <div class="drk clearfix">
                      <div class="col-1">user registered in past month</div>
                      <div class="col-2"><?php echo $pastmonth ?></div>
                  </div>
                  



                </div>

                <div class="blue clearfix total">

                  
                  <div class="drk clearfix">
                      <div class="col-1">total event friends to date</div>
                      <div class="col-2"><?php echo $totaleventfriendsinvites ?></div>
                  </div>
                  <div class="blue clearfix">
                      <div class="col-1">total friends to date</div>
                      <div class="col-2"><?php echo $totalfriendsinvites ?></div>
                  </div>
                 
                </div>

                  <div class="bottom">

                    <div class="drk clearfix">
                        <div class="col-1">plan usage</div>
                        <div class="col-2">#</div>
                    </div>
                    <?php 
                    $status= strtolower(trim($summaryData->getplansresponse->status));
                   if($status == 'success'){;
                    $c =false;
                    foreach ($summaryData->getplansresponse->plans->plan
 as $plan) {
                    
                    ?>

                    <div class="<?=(($c = !$c)?'blue':'drk')?> clearfix">
                        <div class="col-1"><?= $plan->plan_name ."($plan->plan_amount $plan->plan_currency)" ?></div>
                        <div class="col-2"><?= $plan->user_count?></div>
                    </div>
                    <?php } 
                  }?>
                    

                  </div>

              </div>

              <div class="accnt-right">

                <div class="top">

                  <strong>total  data on S3: <span><?=$MemHelper->toByteString($s3Total->data_usage)?></span></strong>
                  <div class="drk clearfix">
                      <div class="col-6">total of images</div>
                      <div class="col-6">average image size</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-6"><?php echo $s3Total->total_image?></div>
                      <div class="col-6"><?php echo $MemHelper->toByteString($s3Total->average_image);?></div>
                  </div>

                  <div class="drk clearfix">
                      <div class="col-4">total # of video</div>
                      <div class="col-4">average video size</div>
                      <div class="col-4">average duration</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-4"><?php echo $s3Total->total_vedio?></div>
                      <div class="col-4"><?php echo $MemHelper->toByteString($s3Total->average_vedio);?></div>
                      <div class="col-4">10 minutes</div>
                  </div>

                  <div class="drk clearfix">
                      <div class="col-4">total # of audio</div>
                      <div class="col-4">average audio size</div>
                      <div class="col-4">average duration</div>
                  </div>
                  <div class="blue clearfix mb-10">
                      <div class="col-4"><?php echo $s3Total->total_audio?></div>
                      <div class="col-4"><?php echo $MemHelper->toByteString($s3Total->average_audio)?></div>
                      <div class="col-4">10 seconds</div>
                  </div>

                  <div class="bottom">


                    <div class="drk clearfix">
                        <div class="col-3">invite sent</div>
                        <div class="col-3">day</div>
                        <div class="col-3"> week</div>
                        <div class="col-3">month</div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-3">facebook</div>
                        <div class="col-3"><?php echo $fbpastday ?></div>
                        <div class="col-3"><?php echo $fbpastweek ?></div>
                        <div class="col-3"><?php echo $fbpastmonth ?></div>
                    </div>
                    <div class="drk clearfix">
                        <div class="col-3">twitter</div>
                        <div class="col-3"><?php echo $twpastday ?></div>
                        <div class="col-3"><?php echo $twpastweek ?></div>
                        <div class="col-3"><?php echo $twpastmonth ?></div>
                    </div>
                    <div class="blue clearfix">
                        <div class="col-3">email</div>
                        <div class="col-3"><?php echo $emailpastday ?></div>
                        <div class="col-3"><?php echo $emailpastweek ?></div>
                        <div class="col-3"><?php echo $emailpastmonth ?></div>
                    </div>

                  </div>
                </div>

              </div>

 

    