<?php
	 $action ="/admin/moderate_event/disapprove";

 if($eventStatus == 'inactive') {
	 $action ="/admin/moderate_event/approve";
	 
	 }
?>




<form action="<?=$action?>" method="post" class="change-status" name="form1" id="form1" >
  <input name="event_id" type="hidden" value="<?=$event->event_id?>" >
  <ul id="" class="share_memreas_details">
  <?php if($eventStatus == 'inactive') {?>
    <li>
      <label class="textfield_names">Approve Event :</label>
      <select id="reason" name="reason">
        <option value="no reason">Select Reason</option>
        <option value="admin approved">admin approved</option>
        <option value="subscription update">subscription update</option>
      </select>
    </li>
    <li>
    <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >Approve</a> 
                <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
    </li>
    <?php }else{?>
    
    
    <li>
      <h2>Disapprove Event</h2>
      <label class="textfield_names">Select Reason :</label><li>
        <li>
          <input type="radio" name="reason" value="inappropriate-language" id="il"><label for="il">Inappropriate Language</label></option>
        </li>
        <li>
          <input type="radio" name="reason" value="sexual-content" id="sc"><label for="sc">sexual content</label></option>
        </li>
        <li>
          <input type="radio" name="reason" id="um" value="unauthorized-material"><label for="um">unauthorized material</label></option>
        </li>
        <li>
          <input type="radio" name="reason" id="other" value="other"><label for="other">other</label></option>
        </li>
        <li>
          <textarea name="reason" id="reason_other" cols="30" rows="10"></textarea>
        </li>
   
    <li> <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >Disapprove</a> 
                <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
    </li>
     <?php }?>
   </ul>
</form>
      <script type="text/javascript">
      $('#reason_other').on('focus',function () {
        $('input#other').attr('checked','true');
      });
function checkdata()
  { 

  	if($('#reason').val() == 0){
  		alert('please select reson');
  		    return false;

  		}
  	
    $.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
  $( "#tabone" ).html( data );
  });
  	return true;
  	
  }
   $("#dtp_date").datepicker();
</script>