<?php 
 $sm = $this->getHelperPluginManager()->getServiceLocator();
 
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);

//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  


?> 

  <div class="manage-event"><p>moderate events</p><div class="total">
  <p>Total Events:<?php echo $event_total ?></p></div></div>
            <div class="username"><p>user</p>
            
                  </div>
            <div class="clr"></div>
                  <table id="eventTbl" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0">
                  <thead>
  <tr>
    <th>profile pic</th>
    <th><a href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'username', 'order' => $url_order)));?>">username</th>
    <th><a href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'name', 'order' => $url_order)));?>">event name</th>
    <th>event media </th>
    <th>viewable</th>
    <th>Action</th>
    
  </tr>
  </thead>
   
    
              
<?php 
 $MemHelper = $this->Mem();
 foreach ($paginator as $key => $resultset) {
  $img = $MemHelper->ProfilePic($resultset -> metadata);
 ?>
    <tr>
    <td><?php echo '<img src="'. $img.'"/>'; ?>  </td>
    <td><?php echo $resultset -> username ?></td>
    <td><?php echo $resultset -> name ?></td>
    <td><a id="button" class="intab " href="/admin/moderate_event/media/<?php echo $resultset -> event_id?>" >view media</a></td>
    <td><?php echo $MemHelper->showDate($resultset -> viewable_from). ' - '. $MemHelper->showDate($resultset -> viewable_to) .'-'.$MemHelper->showDate($resultset -> self_destruct)?> </td>
    
 <th><a class="intab" href="/admin/moderate_event/changeStatus/<?=$resultset ->event_id?>">Disapprove</a></th>

      
  </tr>

    
   
   <?php  }?>
   </table>
   <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml',
    //the route to link to when a user clicks a control link
    array(                'order_by'=>$order_by,'order' => $order,'q'=>$q
          )
);
?>
<script>
function changeEventStatus(eventid){
	alert(eventid);
	
	}
</script>