
<div id="tab3" class="hideCls">
        <div class="span12">
          <aside id="left">
            <figure class="event">
              <div class="fotorama image-preview" data-click="false" data-swipe="true" data-ratio="800/725" data-max-width="100%" data-height="50%" data-allow-full-screen="true"  data-nav="thumbs">
                <a  href="https://api.fnkr.net/testimg/550x400/4682B4/FFF?text=First+Image" /><img src="https://api.fnkr.net/testimg/150x100/4682B4/FFF?text=First+Image"></a>
                <a  href="https://api.fnkr.net/testimg/550x400/4682B4/FFF?text=First+Image" /><img src="https://api.fnkr.net/testimg/150x100/4682B4/FFF?text=First+Image"></a>
                <a  href="https://api.fnkr.net/testimg/550x400/4682B4/FFF?text=First+Image" /><img src="https://api.fnkr.net/testimg/150x100/4682B4/FFF?text=First+Image"></a>
                <a  href="https://api.fnkr.net/testimg/550x400/4682B4/FFF?text=First+Image" /><img src="https://api.fnkr.net/testimg/150x100/4682B4/FFF?text=First+Image"></a>
                <a  href="https://api.fnkr.net/testimg/550x400/4682B4/FFF?text=First+Image" /><img src="https://api.fnkr.net/testimg/150x100/4682B4/FFF?text=First+Image"></a>
               

              </div>
            </figure>
          </aside>
        </div>
        
        <div class="clear"></div>
        <div class="row-fluid">
          <ul id="carousel" class="elastislide-list">
            <?php 

$MemHelper = $this->Mem();

    foreach ($this->medias as  $media) {
                $json_array = json_decode ($media->metadata, true );
             if(isset($json_array ['S3_files'] ['type'] ['image']))  
             { 
              $mediaUrl = $MemHelper->EventPic($media->metadata);

 
              ?>
        
               <li data-preview="<?=$mediaUrl?>"><a href="#"><img src="<?=$mediaUrl?>" alt="image01" /></a></li>
               <img width= '300' src="" alt="">
               
        <?php }else{ ?>
         <a data-video="true" href="/jwplayer/index.html"><img src="<?=$mediaUrl?>"></a>
        
            

             
         <?php  
     }  } 
 ?>
           
              </ul>
        </div>
        
    </div>
    <script type="text/javascript">
      
      // example how to integrate with a previewer
      var current = 0,
        $preview = $( '#preview' ),
        $carouselEl = $( '#carousel' ),
        $carouselItems = $carouselEl.children(),
        carousel = $carouselEl.elastislide( {
          current : current,
          minItems : 10,
          onClick : function( el, pos, evt ) {

            changeImage( el, pos );
            evt.preventDefault();

          },
          onReady : function() {

            changeImage( $carouselItems.eq( current ), current );
            
          }
        } );

      function changeImage( el, pos ) {

        $preview.attr( 'src', el.data( 'preview' ) );
        $carouselItems.removeClass( 'current-img' );
        el.addClass( 'current-img' );
        carousel.setCurrent( pos );

      }



  </script>