

        <div class="span12">
          
             
              <div class="image-preview">
                <a href="img/large/1.jpg" class="swipebox" title="photo-2"><img id="preview" data-preview="img/large/1.jpg" 
                  style="min-width: 280px;" alt="" /></a>
              </div>
            
            <ul id="carousel" class="elastislide-list">
            <?php 

$MemHelper = $this->Mem();

    foreach ($this->medias as  $media) {
                $json_array = json_decode ($media->metadata, true );
             if(isset($json_array ['S3_files'] ['type'] ['image']))  
             { 
              $mediaUrl = $MemHelper->EventPic($media->metadata);

 
              ?>
        
               <li data-preview="<?=$mediaUrl?>"><a href="#"><img src="<?=$mediaUrl?>" alt="image01" /></a></li>
                
        <?php }else{ 
$mediaUrl = $MemHelper->EventPic($media->metadata);

          ?>
         <a data-video="true" href="/jwplayer/index.html"><img src="<?=$mediaUrl?>"></a>
        
            

             
         <?php  
     }  } 
 ?>
           
              </ul>
    
        </div>
        
        <div class="clear"></div>
         
          
       
    
    <script type="text/javascript">
intiElastic();
    </script>