 <?php 
if(empty($this->feedback)){
	echo "no record found<>";return;
	}
       ?>

   
            
        
              <li>
            <label class="textfield_names1">name :</label>
            
            <input name="name" type="text" class="share-txtfield1" value="<?php echo $feedback->name?>" >
            </li>
              <li>
            <label class="textfield_names1">message :</label>
             
            <textarea name="message" class="share-txtfield1" cols="40" rows="10"><?php echo $feedback->message?></textarea>
            </li>

            <li>
            <label class="textfield_names1">email :</label>
            <input name="email" type="text" class="share-txtfield1" value="<?php echo $feedback->email?>">
            </li>

            <li>
            <label class="textfield_names1">create_time :</label>
            <input name="create_time" type="text" class="share-txtfield1" value="<?php echo $feedback->create_time?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" >
            </li>
             
  