       <?php 
if(empty($this->feedback)){
	echo "no record found";return;
	}
       ?>

<div id="tab3" class="hideCls">
        <div class="span7">
          
            
           <ul id="preview" class="right scrollClass change-status">
               <li>
            <label class="textfield_names1">profile photo :</label>
            <?php
            $MemHelper = $this->Mem();
                
            echo '<img src="'. $MemHelper->ProfilePic($feedback-> metadata).'" width="56px"/>'; 
            ?>
            
            </li>
              <li>
            <label class="textfield_names1">name :</label>
            
            <input name="name" type="text" class="share-txtfield1" value="<?php echo $feedback->name?>" >
            </li>
              <li>
            
             
            <textarea name="message" class="share-txtfield1" cols="40" rows="10"><?php echo $feedback->message?></textarea>
            </li>

            <li>
            <label class="textfield_names1">email :</label>
            <input name="email" type="text" class="share-txtfield1" value="<?php echo $feedback->email?>">
            </li>

            <li>
            <label class="textfield_names1">create_time :</label>
            <input name="create_time" type="text" class="share-txtfield1" value="<?php echo $feedback->create_time?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" >
            </li>
             
           
            </ul>
                 
            
          
        </div>
        
        <div class="clear"></div>
        <div class="row-fluid">
          <ul id="carousel" class="elastislide-list">
            <?php 

$MemHelper = $this->Mem();

    foreach ($paginator as $key => $resultset) {?>
                
               <li data-preview="/admin/report_feedback/detail/<?php echo $resultset->feedback_id?>"><a href="#">
                <p><?php echo $resultset->message ?></p></a></li>
               
            

             
         <?php  
     }  
 ?>
           
              </ul>
        </div>
        
    </div>
    <script type="text/javascript">
      
      // example how to integrate with a previewer
      var current = 0,
        $preview = $( '#preview' ),
        $carouselEl = $( '#carousel' ),
        $carouselItems = $carouselEl.children(),
        carousel = $carouselEl.elastislide( {
          current : current,
          minItems : 10,
          onClick : function( el, pos, evt ) {

            changeImage( el, pos );
            evt.preventDefault();

          },
          onReady : function() {

           // changeImage( $carouselItems.eq( current ), current );
            
          }
        } );

      function changeImage( el, pos ) {
		    $('#preview').empty();
        $('#preview').load(el.data( 'preview' ));
       // $preview.attr( 'src', el.data( 'preview' ) );
        $carouselItems.removeClass( 'current-img' );
        el.addClass( 'current-img' );
        carousel.setCurrent( pos );

      }

  </script>
          
      

<script type="text/javascript">
<?php if(!empty($this->messages)){?>
	jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');

<?php 	}?>
</script>