<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Memreas</title>

<!--Custom css-->
<link href="/css/style.css" rel="stylesheet" type="text/css">
<link href="/css/jquery.mCustomScrollbar.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="/css/elastislide.css" />

<link rel="stylesheet" href="/css/swipebox.css">
<link href="/css/fotorama.css" rel="stylesheet">

<link href="/css/jquery.akordeon.css" rel="stylesheet" type="text/css" />

<!--Bootstrap Css-->
<link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="/css/datepicker.css" rel="stylesheet" type="text/css">

<!--jQuery Lybrary-->
<script src="/js/jquery.js"></script>
<script src="/js/modernizr.custom.17475.js"></script>

<!--Bootstrap jQuery-->
<script src="/js/bootstrap.min.js"></script>
<script src="/js/fotorama.js"></script>

<script src="/js/bootstrap-datepicker.js"></script>
<script src="/js/jNotify.jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/jNotify.jquery.css" media="screen" />
<script src="/js/global.js"></script>


<script type="text/javascript">
$(function() {
$( "#datepicker" ).datepicker();
$( "#datepicker-1" ).datepicker();
$( "#datepicker-2" ).datepicker();
$( "#datepicker-3" ).datepicker();
});
</script>

<!--Backgound Strecher-->
<script type="text/javascript" src="/js/bgstretcher.js"></script>
<script type="text/javascript">
$(document).ready(function(){
$(document).bgStretcher({
			images: ['/img/bg.jpg'],
			imageWidth: 1366, imageHeight: 700
		});
	});
</script>

</head>

<body>
<!-- Begin : Container -->
<div class="container">
  <!-- Begin : Header -->
  <div class="row-fluid">
  	<header>
      <h1 id="logo"><a href="index.html">memreas</a></h1>
      <input name="input" type="text" class="search_bar" value="@person, #discover" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == '@person, #discover')this.value = '';"/>
      <a href="notifications.html" class="notification_icon"></a>
      <div class="pro-info">
      	<figure class="pro-pic"><img src="/img/profile-pic.jpg" alt=""></figure>
        <div class="pro-name"><?=$_SESSION['user']['username']?></div>
      </div>
    </header>
  </div>
  <!-- End : Header -->
  <!-- Begin : Content -->
  	<div class="row-fluid content">
    
      <div class="span12 fixed">
      	<div class="row-fluid">
        <ul id="tabs" class="medium_tabs">
            <li><a href="#" title="tab1">manage events</a></li>
            <li><a href="#" title="tab2">manage users</a></li>
            <li><a href="#" title="tab3">manage admins</a></li>
            <li><a href="#" title="tab4">feedback report</a></li>
            <li><a href="#" title="tab5">moderate events</a></li>
            <li><a href="#" title="tab6">Account Summary </a></li>
            <li><a href="#" title="tab7">Account Usage</a></li>
            


        </ul>
        <div id="tab-content">
          <div id="tab1" class="hideCls"></div>
          <div id="tab4" class="hideCls"></div>
          <div id="tab2" class="hideCls"></div>      
          <div id="tab3" class="hideCls" style="display: block;"></div>
          <div id="tab5" class="hideCls"></div>
          <div id="tab6" class="hideCls"></div>
          <div id="tab7" class="hideCls"></div>
             <div id="forgot" class="popups2">
                <a id="forgotClose" onClick="disablePopup('forgot')" class='popupClose'>x</a>
          <div id="tabone" class=""></div>
                
                
            </div>





          <!------------------first-pop-up-------------------->
          		<div id="locationmap" class="popups2">
                  <a id="popupContactClose" onClick="disablePopup('locationmap')" class='popupClose'>x</a>
                    <h2>location</h2>
                    <input name="input"type="text" class="search_bar" value="Search your location" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'Search your location')this.value = '';"/>
                    <div class="clear"></div>
                	<div class="map_box"></div>
                </div>
       

          
          
          
                <div id="bglocationmap" class="backgroundPopup"></div> 
      	</div>
      </div>
    </div>
  <!-- End : Content -->
</div>
<!-- Begin : Footer -->
<footer>&copy; 2013 memreas, llc. All rights reserved.</footer>
<!-- End : Footer -->
<!-- End : Container -->

<script src="/js/jquery.akordeon.js" type="text/javascript"></script>
<script type="text/javascript">
     $(document).ready(function () {
     $('#buttons').akordeon();
       $('#button-less').akordeon({ buttons: false, toggle: true, itemsOrder: [2, 0, 1] });
	 $('#buttons2').akordeon();
       $('#button-less').akordeon({ buttons: false, toggle: true, itemsOrder: [2, 0, 1] });
	 $('#buttons3').akordeon();
       $('#button-less').akordeon({ buttons: false, toggle: true, itemsOrder: [2, 0, 1] });
	 $('#buttons4').akordeon();
       $('#button-less').akordeon({ buttons: false, toggle: true, itemsOrder: [2, 0, 1] });
	 $('#buttons5').akordeon();
       $('#button-less').akordeon({ buttons: false, toggle: true, itemsOrder: [2, 0, 1] });
    });
	
</script>


<!--pop-up-->
<script src="/js/popup.js" type="text/javascript"></script>

<!-- custom scrollbars plugin -->
	<script src="/js/jquery.mCustomScrollbar.concat.min.js"></script>
	<script>
	
		(function($){ 
      
			$(window).load(function(){
$(document).on("click" , "a.paginate_click", function(e){
          e.preventDefault();
          var $this=$(this),
            url=$this.attr("href");
            var target = $(this).parents('div .hideCls');
            $(target).load( url );
 
 
} );
$(document).on("click" , "a.intab", function(e){
          e.preventDefault();
          var $this=$(this),
          url=$this.attr("href");
          var target = $('#tabone');
		  $(target).empty();
          $(target).load( url );
                  popup('forgot');

         //$("#tab-content div.hideCls").hide(); //Hide all content
          //$(target).show();
 
} );
 
			
			$("ul.scrollClass").mCustomScrollbar({
					scrollButtons:{
						enable:true
					}
				});
				
				
				
				
			$("#tab-content div.hideCls").hide(); // Initially hide all content
			$("#tabs li:first").attr("id","current"); // Activate first tab
			$("#tab-content div:first").fadeIn(); // Show first tab content*/
			
			$('#tabs a').click(function(e) {
 				e.preventDefault();        
				$("#tab-content div.hideCls").hide(); //Hide all content
				$("#tabs li").attr("id",""); //Reset id's
				$(this).parent().attr("id","current"); // Activate this
				$('#' + $(this).attr('title')).fadeIn(); // Show content for current tab
				
			});

			
				
				
				//ajax demo fn
				$("a[rel='load-content']").click(function(e){
					
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").html(data); //load new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly loaded content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","top",{scrollInertia:200}); //scroll to top
					});
				});
				$("a[rel='append-content']").click(function(e){
					e.preventDefault();
					var $this=$(this),
						url=$this.attr("href");
					$this.addClass("loading");
					$.get(url,function(data){
						$this.removeClass("loading");
						$("ul.scrollClass .mCSB_container").append(data); //append new content inside .mCSB_container
						$("ul.scrollClass").mCustomScrollbar("update"); //update scrollbar according to newly appended content
						$("ul.scrollClass").mCustomScrollbar("scrollTo","h2:last",{scrollInertia:2500,scrollEasing:"easeInOutQuad"}); //scroll to appended content
					});
				});
			});
		})(jQuery);
	</script>
    
    <!-- custom swipebox plugin -->    
	<script src="/js/jquery.swipebox.min.js"></script>
	<script type="text/javascript">
		jQuery(function($) {
			$(".swipebox").swipebox();
		});
       
 
 
 $('#tab1').load('/admin/event/index');
  $('#tab2').load('/admin/user');
    $('#tab3').load('/admin/manage-admin');
    $('#tab4').load('/admin/report-feedback');
    $('#tab5').load('/admin/moderate-event');
    



	</script>
  <script>
                    
  
 $(document).on("click" , "a.delMediaLi", function(event) {
        event.preventDefault();
        var r = confirm('Do You Realy Wat to Delete This Item ! '+ event.target.id.slice(4) );
        var  delLink = $(this);
         if(r) {                     $(delLink).closest( "li" ).remove();

            $.post( this.href,function(response){
               if(response=='success'){
                    $(delLink).closest( "li" ).remove();
               }

            });
        }else{

        }
       
      }
    );
  
  
                    </script>
                      <script type="text/javascript" src="/js/jquery.elastislide.js"></script>
  
</body>
</html>
