  <div class="manage-event"><p>manage feedback</p><div class="total"><p>Total Events:67</p></div></div>
            
            <div class="clr"></div>
             <table id="managefeedbacktable" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0">
                  <thead>
  <tr>
    <th>Sr.no</th>
    <th>user_id</th>
    <th>name</th>
    <th>message</th>
    <th>email</th>
    <th>create_time</th>
 
  </tr>
  </thead>
   
<?php 
foreach ($paginator as $key => $feedback) {
    # code..
?>
    <tr>
    <td> <?php echo $key+1 ?></td>
    <!--td><?php echo $feedback -> feedback_id ?></td!-->
    <td><?php echo $feedback -> user_id ?></td>
    <td><?php echo $feedback -> name ?></td>
    <td><?php echo $feedback -> message ?></td>
    <td><?php echo $feedback -> email ?></td>
    <td><?php echo $feedback -> create_time ?></td>
    
    
<td><a class="intab" href="/admin/feedback/add"><img src="/img/status.png"></a></td>
     <td><a class="intab" href="/admin/feedback/edit/<?php echo $feedback -> feedback_id ?>"><img src="/img/edit.png"></a></td>
    <td><a class="intab" href="/admin/feedback/view/<?php echo $feedback -> feedback_id ?>"><img src="/img/eye.png"></a></td>
  </tr>

    
   
   <?php  }?>
   </table>

   <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array()
);
?>
