       <?php

       ?>
          <form id="form1" name="form1"  action="/admin/feedback/edit" method="post" enctype="multipart/form-data" name="addfeedbackFrm">
          <div class="manage-event"><p>edit feedback</p></div>
            <ul id="content_1" class="share_memreas_details scrollClass mCustomScrollbar _mCS_1"><div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;"><div class="mCSB_container mCS_no_scrollbar" style="position: relative; top: 0px;">
            <li>
            <input id="id" name="id" value="<?php echo $this->feedback->feedback_id?>" type="hidden">
            <label class="textfield_names1">feedback_id :</label>
            <input id="feedback_id" name="feedback_id" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->feedback_id?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
             <li>
            <label class="textfield_names1">user_id :</label>
            <input id="user_id" name="user_id" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->email?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
              <li>
            <label class="textfield_names1">name :</label>
            <input name="name" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->name?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
              <li>
            <label class="textfield_names1">message :</label>
            <input name="message" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->message?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>

            <li>
            <label class="textfield_names1">email :</label>
            <input name="email" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->email?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>

            <li>
            <label class="textfield_names1">create_time :</label>
            <input name="create_time" type="text" class="share-txtfield1" value="<?php echo $this->Feedback->create_time?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
            
            
              
           
           
            </div><div class="mCSB_scrollTools" style="position: absolute; display: none;"><a class="mCSB_buttonUp" oncontextmenu="return false;"></a><div class="mCSB_draggerContainer"><div class="mCSB_dragger" style="position: absolute; top: 0px;" oncontextmenu="return false;"><div class="mCSB_dragger_bar" style="position:relative;"></div></div><div class="mCSB_draggerRail"></div></div><a class="mCSB_buttonDown" oncontextmenu="return false;"></a></div></div></ul>
                  <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >save feedback</a> 
                <a class="black_btn_skin" href="#" >cancel</a>
            
            
          
          </form>
      

<script type="text/javascript">
jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');
function checkdata()
{ 

	var getnm = trim(document.getElementById("username").value);
        var email = trim(document.getElementById("email").value);
	
	if(getnm == "" || email == "")
	{
		alert("Please fill all the value properly.");return false;
	}
        var email = document.getElementById('email');
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
    }
	
  $.post(document.form1.action, $('#form1').serialize(), function( data ) {
$( "#tab2" ).html( data );
});
	return true;
	
}

function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
function resetdata()
{
    	document.getElementById("username").value="";
        document.getElementById("email").value="";
}

</script>