 <?php
$transaction_request = json_decode(trim($orderData->getorderresponse->order->transaction_request));
$transaction_response = json_decode(trim($orderData->getorderresponse->order->transaction_response));
$user = json_decode(trim($orderData->getorderresponse->order->user_detail));
$tansaction_type = trim($orderData->getorderresponse->order->transaction_type);
$amount ='';
 $MemHelper = $this->Mem();

//echo '<pre>';
///print_r($orderData);
echo "<h2>$tansaction_type </h2>";
//exit;
if($tansaction_type == 'buy_subscription'){
 
 ?>

 <ul id="" class="share_memreas_details">
              <li>
            <label class="textfield_names1">name :</label>
            <label class=""><?php echo $user->first_name. ' ' .$user->last_name?></label>
            </li>
              <li>
            <label class="textfield_names1">address :</label>
             
            <label class=""><?php echo $user->address_line_1?></label>
            </li>
            <li>
            <label class="textfield_names1">address2 : <?php echo $user->address_line_2?> </label>
            </li>
            <li>
            <label class="textfield_names1">card type :</label>
            
            <label class=""><?php echo 
             $transaction_request->card_type ?> </label>
            </li>
            
            <li>
            <label class="textfield_names1">card number :</label>
            <label class=""><?php echo $transaction_request->obfuscated_card_number?>  </label>
            </li>
            <li>
            <label class="textfield_names1">Expire on :</label>
            <label class=""><?php echo $transaction_request->exp_month."/".$transaction_request->exp_year?></label>
            </li>
            
            <li>
                  <li>
            <label class="textfield_names1">City :</label>
            <label class=""><?php echo $user->city?></label>
            </li>
            <li>
            <label class="textfield_names1">State :</label>
            <label class=""><?php echo $user->state?></label>
            </li>
            <label class="textfield_names1">amount:</label>
            <label class=""><?php echo $amount?></label>
            </li>
            <li>
            <label class="textfield_names1">Zip :</label>
            <label class=""><?php echo $user->zip_code?></label>
            </li>
            <li>
            <label class="textfield_names1">plan Name :</label>
            <label class=""><?php echo $transaction_response->plan->name?></label>
            </li>
            <li>
            <label class="textfield_names1">cost :</label>
            <label class=""><?php echo $transaction_response->plan->amount?></label>
            </li>
             
  </ul>
  <?php } else if($tansaction_type == 'add_value_to_account') {  ;?>

   <ul id="" class="share_memreas_details">
              <li>
            <label class="textfield_names1">name :</label>
            <label class=""><?php echo $transaction_response->card->name?></label>
            </li>
              <li>
            <label class="textfield_names1">address :</label>
             
            <label class=""><?php echo $transaction_response->card->address_line1?></label>
            </li>
            <li>
            <label class="textfield_names1">address2 : <?php echo $transaction_response->card->address_line2?> </label>
            </li>
            <li>
            <label class="textfield_names1">card type :</label>
            
            <label class=""><?php echo 
             $transaction_response->card->type?> </label>
            </li>
            <li>
            <label class="textfield_names1">card number :</label>
            <label class=""><?php echo $transaction_response->card->last4?>  </label>
            </li>
            <li>
            <label class="textfield_names1">Expire on :</label>
            <label class=""><?php echo $transaction_response->card->exp_month."/".$transaction_response->card->exp_year?></label>
            </li>
            
            <li>
                  <li>
            <label class="textfield_names1">City :</label>
            <label class=""><?php echo $transaction_response->card->address_city?></label>
            </li>
            <li>
            <label class="textfield_names1">State :</label>
            <label class=""><?php echo $transaction_response->card->address_state?></label>
            </li>
            <label class="textfield_names1">amount:</label>
            <label class=""><?php echo $transaction_response->amount?></label>
            </li>
            <li>
            <label class="textfield_names1">Zip :</label>
            <label class=""><?php echo $user->zip_code?></label>
            </li>
            <li>
            <label class="textfield_names1">Captured :</label>
            <label class=""><?php echo ($transaction_response->captured == 1)?'yes':'no'?></label>
            </li>
            <li>
            <label class="textfield_names1">Paid :</label>
            <label class=""><?php echo ($transaction_response->paid == 1)?'yes':'no'?></label>
            </li>
            <li>
            <label class="textfield_names1">Amount  :</label>
            <label class=""><?php echo $transaction_response->amount . ' '. $transaction_response->currency?></label>
            </li>
            <li>
            <label class="textfield_names1">Created  :</label>
            <label class=""><?php echo $MemHelper->showDate($transaction_response->created) ?></label>
            </li>
             
  </ul>
   <?php } else if($tansaction_type == 'store_credit_card') { ?>
            <ul id="" class="share_memreas_details">
              <li>
            <label class="textfield_names1">name :</label>
            <label class=""><?php echo $user->first_name. ' ' .$user->last_name?></label>
            </li>
              <li>
            <label class="textfield_names1">address :</label>
             
            <label class=""><?php echo $transaction_response->address_line1?></label>
            </li>
            <li>
            <label class="textfield_names1">address2 : <?php echo $transaction_response->address_line2?> </label>
            </li>
            <li>
            <label class="textfield_names1">card type :</label>
            
            <label class=""><?php echo $transaction_response->type ?> </label>
            </li>
            
            <li>
            <label class="textfield_names1">card number :</label>
            <label class=""><?php echo $transaction_response->last4?>  </label>
            </li>
            <li>
            <label class="textfield_names1">Expire on :</label>
            <label class=""><?php echo $transaction_response->exp_month."/".$transaction_response->exp_year?></label>
            </li>
            
            <li>
                  <li>
            <label class="textfield_names1">City :</label>
            <label class=""><?php echo $user->city?></label>
            </li>
            <li>
            <label class="textfield_names1">State :</label>
            <label class=""><?php echo $user->state?></label>
            </li>
             
            <li>
            <label class="textfield_names1">Zip :</label>
            <label class=""><?php echo $user->zip_code?></label>
            </li>
            
  </ul>
<?php } else if($tansaction_type == 'refund_amount') {  ;?>

   <ul id="" class="share_memreas_details">
              <li>
            <label class="textfield_names1">name :</label>
            <label class=""><?php echo $transaction_response->username?></label>
            </li>
              <li>
            <label class="textfield_names1">address :</label>
             
            <label class=""><?php echo $user->address_line_1?></label>
            </li>
            <li>
            <label class="textfield_names1">address2 : <?php echo $user->address_line_2?> </label>
            </li>
            <li>
            <label class="textfield_names1">reason :</label>
            
            <label class=""><?php echo 
             $transaction_response->reason?> </label>
            </li>
            
           
            
           
                  <li>
            <label class="textfield_names1">City :</label>
            <label class=""><?php echo $user->city?></label>
            </li>
            <li>
            <label class="textfield_names1">State :</label>
            <label class=""><?php echo $user->state?></label>
            </li>
             <li>
            <label class="textfield_names1">balance:</label>
            <label class=""><?php echo $transaction_response->balance?></label>
            </li>
            <li>
            <label class="textfield_names1">Zip :</label>
            <label class=""><?php echo $user->zip_code?></label>
            </li>
            
            <li>
            <label class="textfield_names1">Amount  :</label>
            <label class=""><?php echo $orderData->getorderresponse->order->amount //. ' '. $transaction_response->currency?></label>
            </li>
            
             
  </ul>
   <?php } ?>