<div>
                         <div class="required"> 
 Feedback Description</div>
 
<ul class="personresults">
    <?php 
    use Application\Model\MemreasConstants;
     $MemHelper = $this->Mem();

    foreach ($this->medias as  $media) {
        ?>
    
<li><figure class="pro-pics"><img src="<?=$MemHelper->EventPic($media->metadata)?>" alt=""></figure>
</li>

 <?php } ?>

</ul>
                    </div>
                     
                    
                   