  <div class="manage-event"><p>order history</p>
    <!-- <div class="total"><p>Total feedback:<?php echo $feedback_total ?></p></div> -->
  </div>
            
            <div class="clr"></div>
             <table id="managefeedbacktable" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0">
                  <thead>
  <tr>
    <th>order#</th>
    <th>date of order</th>
        <th>transaction type</th>

    <th>Plan Name</th>
    <th>Action</th>

  </tr>
  </thead>
   
<?php 
 //$MemHelper = $this->Mem();

foreach ($orderData->getorderhistoryresponse->orders->order as $row) {
  $transaction_response = json_decode($row->transaction_response);
$plan = isset($transaction_response->plan->name)?$transaction_response->plan->name:'';
   
 ?>
    <tr>
    <td>#</td>
    <td><?php echo $row ->transaction_receive ?></td>
        <td><?php echo $row ->transaction_type ?></td>

    <td><?php echo $plan ?></td>
    
 <th><a class="intab" href="/admin/OrderHistory/detail/<?=$row->transaction_id?>">view</a></tr>

    
   
   <?php  }?>
<tr><td colspan="5" align="left" class="drk">



  <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo ($page>1)?$page-1:1;?>">< Previous</a>
<?php 
for($i=1;$i<=$page;$i++){
  if($i==$page){
        echo " <span class='count'>$i</span> |";

  }else{
   echo "<a class='paginate_click' href='/admin/OrderHistory?page=".$i."'>$i</a> |"; 
    }
  }
?>

  <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo $page+1;?>">Next ></a>


 <?php 
  // add at the end of the file after the table
/*echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array(                'order_by'=>$order_by,'order' => $order,'q'=>$q
          )
);*/
?>

</td></tr>


   </table>

 