<?php 
$form = $this->form;
$form->setAttribute('action',$this->url);
$form->prepare();

echo $this->form()->openTag($form);?>
         
<div class="required"> 
Event Details</div>

                    <ul id="content_1" class="share_memreas_details">
                    
<?php foreach ($form as $element) :
?>
<li>
            <label class="textfield_names <?php if($this->formElementErrors($element)) 
                                echo "error" ?>"><?php echo $element->getLabel() ?>
                            </label>
            <?php echo $this->formElement($element);?>
            
        		<?php if($this->formElementErrors($element)) :?>
                    <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    		      <?php endif ?> 
            </li>
 

<?php
endforeach;?>


<?php echo $this->form()->closeTag($form); ?>