<?php if ($this->pageCount): 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);
//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  $pagination_class = isset($pageClass) ? $pageClass :'paginate_click';
?>

<?php if ($this->pageCount): ?>
<ul >
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
                    <li><a class="<?=$pagination_class?>" href="<?php echo $this->url($this->route,$routeparams,array('query' => array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order))); ?>">
    &lt; Previous
  </a> </li>
<?php else: ?>
  <li><span >&lt; Previous<span></li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
          <li><a class="<?=$pagination_class?>" href="<?php echo $this->url($this->route, $routeparams ,array('query' => array('page' => $page, 'order_by' => $order_by, 'order' => $order)));?>">
        <?php echo $page; ?>
    </a> </li>
  <?php else: ?>
   <li class="active"> <span ><?php echo $page; ?></span></li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
       <li> <a class="<?=$pagination_class?>" href="<?php echo $this->url($this->route,$routeparams, array('query' => array('page' => $this->next, 'order_by' => $order_by, 'order' => $order))); ?>">
    Next &gt;
  </a></li>
<?php else: ?>
  <li><span class="disabled">Next &gt;</span></li>
<?php endif; ?>
</ul>
<?php endif; ?>

<?php endif; ?>