<?php if ($this->pageCount): 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);
//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  
?>

<?php if ($this->pageCount): ?>
<div class="count">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
                    <a class="paginate_click" href="<?php echo $this->url($this->route,$routeparams,array('query' => array('page' => $this->previous, 'order_by' => $order_by, 'order' => $order))); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
          <a class="paginate_click" href="<?php echo $this->url($this->route, $routeparams ,array('query' => array('page' => $page, 'order_by' => $order_by, 'order' => $order)));?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
        <a class="paginate_click" href="<?php echo $this->url($this->route,$routeparams, array('query' => array('page' => $this->next, 'order_by' => $order_by, 'order' => $order))); ?>">
    Next &gt;
  </a>
<?php else: ?>
  <span class="disabled">Next &gt;</span>
<?php endif; ?>
</div>
<?php endif; ?>

<?php endif; ?>