          <form action="/admin/user/add" method="post" enctype="multipart/form-data" name="addUserFrm">
          <div class="manage-event"><p>edit users</p></div>
            <ul id="content_1" class="share_memreas_details scrollClass mCustomScrollbar _mCS_1"><div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;"><div class="mCSB_container mCS_no_scrollbar" style="position: relative; top: 0px;">
            <li>
            <label class="textfield_names1">name :</label>
            <input name="input" type="text" class="share-txtfield1" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
             <li>
            <label class="textfield_names1">email :</label>
            <input name="input" type="text" class="share-txtfield1" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
              <li>
            <label class="textfield_names1">facebook account :</label>
            <input name="input" type="text" class="share-txtfield1" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
              <li>
            <label class="textfield_names1">twitter account :</label>
            <input name="input" type="text" class="share-txtfield1" value="sample" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
            
            <li>
            <label class="textfield_names1">disable account :</label>
             <input id="demo_box_1" class="css-checkbox" type="radio" name="sel"> <p style="display:inline-block; margin-left:5px;">yes</p> <input name="sel" id="demo_box_1" class="css-checkbox" type="radio" ><p style="display:inline-block; margin-left:8px">no</p>
            
            </li>
              <li>
            <label class="textfield_names1">profile photo :</label><p>yes</p>
            </li>
           
           
            </div><div class="mCSB_scrollTools" style="position: absolute; display: none;"><a class="mCSB_buttonUp" oncontextmenu="return false;"></a><div class="mCSB_draggerContainer"><div class="mCSB_dragger" style="position: absolute; top: 0px;" oncontextmenu="return false;"><div class="mCSB_dragger_bar" style="position:relative;"></div></div><div class="mCSB_draggerRail"></div></div><a class="mCSB_buttonDown" oncontextmenu="return false;"></a></div></div></ul>
                <a class="black_btn_skin f-center" href="#">save user</a> 
                <a class="black_btn_skin" href="#">cancelk</a>
            
          
          </form>  
             