       <?php
        ?>
          <form id="form1" name="form1"  action="/admin/user/edit" method="post" enctype="multipart/form-data" name="addUserFrm">
          <div class="manage-event"><p>edit users</p></div>
            <ul id="content_1" class="share_memreas_details scrollClass mCustomScrollbar _mCS_1"><div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;"><div class="mCSB_container mCS_no_scrollbar" style="position: relative; top: 0px;">
            <li>
            <input id="id" name="id" value="<?php echo $this->user->user_id?>" type="hidden">
            <label class="textfield_names1">name :</label>

            <input readonly id="username" name="username" type="text" class="share-txtfield1" value="<?php echo $this->user->username?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
             <li>
            <label class="textfield_names1">email :</label>
            <input  readonly  id="email" name="email_address" type="text" class="share-txtfield1" value="<?php echo $this->user->email_address?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
               
 
            
             <li>
                 <?php if($this->user->disable_account=='0'){ ?>
                  <label class="textfield_names1">disable account :</label>
            
              <input id="delete" type="button" onclick= "userdisable('<?php echo $this->user->user_id?>')" value="disable"></a> 
                
             <?php    }else{ ?>
            <label class="textfield_names1">active account :</label>
            
              <input id="delete" type="button" onclick= "useractive('<?php echo $this->user->user_id?>')" value="active"></a> 
                 <?php } ?>
            
 
            </li>
              <li>
            <label class="textfield_names1">profile photo :</label>
            <?php
            $MemHelper = $this->Mem();
                
            echo '<img width="56px" src="'. $MemHelper->ProfilePic($this->user -> metadata).'"/>'; 
            ?>
            
            </li>
           
           
            </div><div class="mCSB_scrollTools" style="position: absolute; display: none;"><a class="mCSB_buttonUp" oncontextmenu="return false;"></a><div class="mCSB_draggerContainer"><div class="mCSB_dragger" style="position: absolute; top: 0px;" oncontextmenu="return false;"><div class="mCSB_dragger_bar" style="position:relative;"></div></div><div class="mCSB_draggerRail"></div></div><a class="mCSB_buttonDown" oncontextmenu="return false;"></a></div></div></ul>
                  <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >save user</a> 
                <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
            
            
          
          </form>
      

<script type="text/javascript">
<?php if(!empty($this->messages)){?>
	jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');

<?php 	}?>

function checkdata()
{ 

	var getnm = trim(document.getElementById("username").value);
        var email = trim(document.getElementById("email").value);
	
	if(getnm == "" || email == "")
	{
		alert("Please fill all the value properly.");return false;
	}
        var email = document.getElementById('email');
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
    }
	
  $.post(document.form1.action, $('#form1').serialize(), function( data ) {
$( "#tabone" ).html( data );
});
	return true;
	
}

function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
function resetdata()
{
    	document.getElementById("username").value="";
        document.getElementById("email").value="";
}
function userdisable (user_id) {
  

    var target = $('#tabone');
    var url = "/admin/user/deactive/"+user_id;
      $(target).empty();
          $(target).load( url );
                  popup('forgot');

  
}

function useractive (user_id) {
  

    var target = $('#tabone');
    var url = "/admin/user/active/"+user_id;
      $(target).empty();
          $(target).load( url );
                  popup('forgot');

  
}

</script>