  <div class="manage-event"><p>manage users</p><div class="total"><p>Total Events:<?php echo $user_total ?></p></div></div>
            
            <div class="clr"></div>
             <table id="manageusertable" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0">
                  <thead>
  <tr>
    <th>Id</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Profile Photo</th>
    <th>Facebook User Name</th>
    <th>Twitter Usern Name</th>
    <th>Role</th>
    <th>Status</th>
    
    <th>Action</th>
 
  </tr>
  </thead>
   
<?php 
foreach ($paginator as $key => $user) {
    # code..
?>
    <tr>
    <td> <?php echo $key+1 ?></td>
    <td><?php echo $user -> username ?></td>
    <td><?php echo $user -> email_address ?></td>
    <td><?php echo $user -> profile_photo ?></td>
    <td><?php echo $user -> facebook_username ?></td>
    <td><?php echo $user -> twitter_username ?></td>
    <td><?php echo $user -> role ==1 ?'admin':'member' ?></td>
    <td><?php
        echo ($user ->disable_account == 0)?'<img src="/img/status.png" />':
		'<img src="/img/cross.png" />'
		; 
     ?>
    </td>
    
<td><a class="intab" href="/admin/user/edit/<?php echo $user -> user_id ?>"><img src="/img/edit.png" /></a><!--<a class="intab" href="/admin/user/view/<?php echo $user -> user_id ?>"><img src="/img/eye.png" /></a>
<a class="intab" href="/admin/user/view/<?php echo $user -> user_id ?>"><img src="/img/cross.png" /></a>--></td>
     
  </tr>

    
   
   <?php  }?>
   </table>

   <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array()
);
?>
