 <?php 
use Application\Model\user;
  $sm = $this->getHelperPluginManager()->getServiceLocator();
 
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);

//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  


?>           
            <div class="clr"></div>
             <table id="manageusertable" class="manageusertable" width="90%" border="1" align="center" cellpadding="0" cellspacing="0"><a href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'username', 'order' => $url_order)));?>">
                  <thead>
  <tr>
    <th>Id</th>
    <th><a class="paginate_click" href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'username', 'order' => $url_order)));?>">User Name </a></th>
    <th><a class="paginate_click" href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'email_address', 'order' => $url_order)));?>">Email</a></th>
    <th>Profile Photo</th>
    <th>Facebook User Name</th>
    <th>Twitter Usern Name</th>
    <th><a class="paginate_click" href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'role', 'order' => $url_order)));?>">Role</th>
    <th><a class="paginate_click" href="<?php echo $this->url('admin/default',$routeparams,array('query' => array('page' => $page, 'order_by' => 'disable_account', 'order' => $url_order)));?>">Status</th>
    
    <th>Action</th>
 
  </tr>
  </thead>
   
<?php 
foreach ($paginator as $key => $user) {
    # code..
?>
    <tr>
    <td> <?php echo $key+1 ?></td>
    <td><?php echo $user -> username ?></td>
    <td><?php echo $user -> email_address ?></td>
    <td><?php echo $user -> profile_photo ?></td>
    <td><?php echo $user -> facebook_username ?></td>
    <td><?php echo $user -> twitter_username ?></td>
    <td><?php echo user::$role_name[$user -> role]  ?></td>
    <td><?php
        echo ($user ->disable_account == 0)?'<img src="/img/status.png" />':
		'<img src="/img/cross.png" />'
		; 
     ?>
    </td>
    
<td><a class="intab" href="/admin/user/edit/<?php echo $user -> user_id ?>"><img src="/img/edit.png" /></a><!--<a class="intab" href="/admin/user/view/<?php echo $user -> user_id ?>"><img src="/img/eye.png" /></a>
<a class="intab" href="/admin/user/view/<?php echo $user -> user_id ?>"><img src="/img/cross.png" /></a>--></td>
     
  </tr>

    
   
   <?php  }?>
   </table>

   <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array(                'order_by'=>$order_by,'order' => $order,'q'=>$q
          )
);
?>
