<form  id="form1" action="/admin/manage_admin/activate" class="change-status" method="post">
    <input type="hidden" name="id" value="<?php echo $user['user_id']; ?>" />
<ul id="" class="share_memreas_details"> 
        <li>
          <h2>activate Admin user </h2>
          <label class="textfield_names">Select Reason :</label>
        </li>
        <li>
          <input type="radio" name="reason" value="available" id="il"><label for="il">available</label></option>
        </li>
        <li>
          <input type="radio" name="reason" id="other" value="other"><label for="other">other</label></option>
        </li>
        <li>
          <textarea name="reason" id="reason_other" cols="30" rows="10"></textarea>
        </li>
        <li>
            <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >Yes</a> 
            <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
        </li>
    </ul>
</form>
<script type="text/javascript">
    <?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$messages) ?>');
    
    <?php  }else {?>
        jsuccessAndRefresh('<?php echo implode (' ',$messages) ?>');
    <?php }
    
    
    }?>
    
function checkdata()
{ var reason = $("input[name='reason']:checked").val();
    if(!reason){
        alert('please select reson');
            return false;

        }else if(reason == 'other'){
                    var txt = $("#reason_other").val();
                     
                    if(!txt.trim()){
                        alert ('please give reason ');
                          return false;
                    }
                    
                }
    $.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
         //show in pop up
        $( "#tabone" ).html( data );
});
    return true;
    
}

</script>

