       <form id="adminaddfrm" action="/admin/manage_admin/addadmin" method="post" enctype="multipart/form-data" name="addUserFrm">
          <div class="manage-event"><p>add admin</p></div>
            <ul id="content_1" class="share_memreas_details scrollClass mCustomScrollbar _mCS_1"><div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;"><div class="mCSB_container mCS_no_scrollbar" style="position: relative; top: 0px;">
            <li>
            <label class="textfield_names1">username :</label>
            <input id="username" name="username" type="text" class="share-txtfield1" value="" placeholder="Username">
            </li>
             <li>
            <label class="textfield_names1">email :</label>
            <input  id="email" name="email_address" type="text" class="share-txtfield1" value="" placeholder="Email">
            </li>
              <li>
            <label class="textfield_names1">Password :</label>
            <input name= "password" type="text" class="share-txtfield1" value="" placeholder="Password">
            </li>
                        
            
            <li>
            <label class="textfield_names1">account type:</label>
              <select name="role">
                <option value="">Select...</option>
                <option value="1">Admin</option>
                <option value="2">Member</option>
                 <option value="3">Superadmin</option>
              </select>
            </li>
              <li>
            <label class="textfield_names1">profile photo :</label><p>no</p>
            </li>
           
           
            </div><div class="mCSB_scrollTools" style="position: absolute; display: none;"><a class="mCSB_buttonUp" oncontextmenu="return false;"></a><div class="mCSB_draggerContainer"><div class="mCSB_dragger" style="position: absolute; top: 0px;" oncontextmenu="return false;"><div class="mCSB_dragger_bar" style="position:relative;"></div></div><div class="mCSB_draggerRail"></div></div><a class="mCSB_buttonDown" oncontextmenu="return false;"></a></div></div></ul>
                <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >save user</a> 
                <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
            
          
          </form>
        
<script type="text/javascript">
<?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$this->messages) ?>');
	
    <?php }else {?>
       jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');
    <?php }
    
    
    }?>

function checkdata()
{ 

	var getnm = trim(document.getElementById("username").value);
        var email = trim(document.getElementById("email").value);
	
	if(getnm == "" || email == "")
	{
		alert("Please fill all the value properly.");return false;
	}
        var email = document.getElementById('email');
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
    }
   $.post($('#adminaddfrm').attr('action'), $('#adminaddfrm').serialize(), function( data ) {
$( "#tabone" ).html( data );
});
	return true;
	
}

function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
function resetdata()
{
    	document.getElementById("username").value="";
        document.getElementById("email").value="";
}

</script>