<?php

$title = 'deactivate admin';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to deactivate
    '<?php echo $this->escapeHtml($user['username']); ?>'
</p>

<form  id="form1" action="/admin/manage_admin/deactivate" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $user['user_id']; ?>" />
    <input type="submit" name="del" value="Yes" onclick="checkdata()" />
    <input type="submit" name="del" value="No" />
    <select id="reason" name="reason" style="display:inline-block; margin-left:8px">
                <option value="0">select reason</option>
                <option value="unavailable">unavailable</option>
                <option value="other">other</option>
            </select>
</div>
</form>
<script>
    <?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$this->messages) ?>');
	
    <?php }else {?>
       jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');
    <?php }
    
    
    }?>
    
function checkdata()
{ 
    $.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
         //show in pop up
        $( "#tabone" ).html( data );
});
	return true;
	
}

</script>