 <?php 
if(empty($row)){
	echo "no record found";return;
	}
       ?>

   
            
        
              <li>
            <label class="textfield_names1">log id:</label>
            
            <input name="log_id" type="text" class="share-txtfield1" value="<?php echo $row->log_id?>" >
            </li>
              <li>
            <label class="textfield_names1">admin name :</label>
             
            <input name="username" type="text" class="share-txtfield1"  value="<?php echo $row->username?>" >
            </li>

            <li>
            <label class="textfield_names1">log type :</label>
            <input name="log_type" type="text" class="share-txtfield1" value="<?php echo $row->log_type?>">
            </li>

            <li>
            <label class="textfield_names1">created :</label>
            <input name="created" type="text" class="share-txtfield1" value="<?php echo $row->created?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" >
            </li>
            
            <li>
            <label class="textfield_names1">entity id :</label>
            <input name="entity_id" type="text" class="share-txtfield1" value="<?php echo $row->entity_id?>">
            </li>
             
  