        <?php $MemHelper = $this->Mem(); ?>
          <form id="form1" name="form1"  action="/admin/manage_admin/edit" method="post" enctype="multipart/form-data" name="addUserFrm">
          <div class="manage-event"><p>edit admin</p></div>
            <ul id="content_1" class="share_memreas_details scrollClass mCustomScrollbar _mCS_1"><div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;"><div class="mCSB_container mCS_no_scrollbar" style="position: relative; top: 0px;">
            <li>
            <input id="id" name="id" value="<?php  echo $admin['user_id']?>" type="hidden">
            <label class="textfield_names1">profile_photo :</label>
            <?php if ($admin['profile_photo'] == 1) {
              echo '<p>yes</p>';
            } else {
              echo '<p>no</p>';
            }
            ?>
            </li>
             <li>
            <label class="textfield_names1">username :</label>
 
            <input id="username" name="username" type="text" class="share-txtfield1" value="<?php echo $status=='error'? $post['username']:   $admin['username']?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
            </li>
            <li>
            <label class="textfield_names1">email :</label>
            <input id="email" name="email_address" type="text" class="share-txtfield1" value="<?php echo $status=='error'? $post['email_address']:$admin['email_address']?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" onFocus="if(this.value == 'sample')this.value = '';">
 
            </li>
              <li>
                <label class="textfield_names1">admin level :</label>
                <select name="role">
                  <option value="">Select...</option>
                  <option value="1" <?php if($admin['role'] == 1) echo 'selected' ?>   >Admin</option>
                  <option value="2" <?php if($admin['role'] == 2) echo 'selected' ?> >Member</option>
                                    <option value="3" <?php if($admin['role'] == 3) echo 'selected' ?> >SuperAdmin</option>

                </select>
            </li>
            <li>
            <label class="textfield_names1">disable account :</label>
              <input id="delete" type="button" onclick= "admindelete()" value="delete"></a> 
             
            
 
            </li>
            
              <li>
            <label class="textfield_names1">date created :</label>
            <input name="" type="text" class="share-txtfield1" 
            value="<?php echo $MemHelper->showDate($admin['create_date'])?>" >
            </li>
            
            
           
           
            </div><div class="mCSB_scrollTools" style="position: absolute; display: none;"><a class="mCSB_buttonUp" oncontextmenu="return false;"></a><div class="mCSB_draggerContainer"><div class="mCSB_dragger" style="position: absolute; top: 0px;" oncontextmenu="return false;"><div class="mCSB_dragger_bar" style="position:relative;"></div></div><div class="mCSB_draggerRail"></div></div><a class="mCSB_buttonDown" oncontextmenu="return false;"></a></div></div></ul>
                  <a class="black_btn_skin f-center" href="#" onclick="checkdata()" >save user</a> 
                <a class="black_btn_skin" href="#" onclick="disablePopup('forgot')">cancel</a>
            
            
          
          </form>
      

<script type="text/javascript">
<?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$this->messages) ?>');
	
    <?php }else {?>
       jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');
    <?php }
    
    
    }?>

function checkdata()
{ 

	var getnm = trim(document.getElementById("username").value);
        var email = trim(document.getElementById("email").value);
	
	if(getnm == "" || email == "")
	{
		alert("Please fill all the value properly.");return false;
	}
        var email = document.getElementById('email');
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
    }
     $( "#tabone" ).addClass("loading");
    $.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
         $( "#tabone" ).removeClass("loading");
         //show in pop up
        $( "#tabone" ).html( data );
});
	return true;
	
}
function admindelete (argument) {
  var adminid=getRadioValue ()
  if (adminid==0) {

alert('please select user');    
  }else{

    var target = $('#tabone');
    var url = "/admin/manage_admin/deactivate/"+adminid;
      $(target).empty();
          $(target).load( url );
                  popup('forgot');

  }
}

function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
function resetdata()
{
    	document.getElementById("username").value="";
        document.getElementById("email").value="";
}

</script>
