       <?php 
if(empty($row)){
	echo "no record found";return;
	}
       ?>

<div id="tab3" class="hideCls">
        <div class="span6">
          
            
           <ul id="preview" class="right scrollClass">
              <li>
            <label class="textfield_names1">log id :</label>
            
            <input name="log_id" type="text" class="share-txtfield1" value="<?php echo $row->log_id?>" >
            </li>
             <li>
            <label class="textfield_names1">admin id :</label>
            
            <input name="admin_id" type="text" class="share-txtfield1" value="<?php echo $row->admin_id?>" >
            </li>

            <li>
            <label class="textfield_names1">log type :</label>
            <input name="log_type" type="text" class="share-txtfield1" value="<?php echo $row->log_type?>" >
            </li>

            <li>
            <label class="textfield_names1">created :</label>
            <input name="created" type="text" class="share-txtfield1" value="<?php echo $row->created?>" onBlur="if(!/\S/.test(this.value))this.value=this.defaultValue" >
            </li>
            
            <li>
            <label class="textfield_names1">entity id :</label>
            <input name="entity_id" type="text" class="share-txtfield1" value="<?php echo $row->entity_id?>">
            </li>
             
           
            </ul>
                 
            
          
        </div>
        
        <div class="clear"></div>
        <div class="row-fluid">
          <ul id="carousel" class="elastislide-list">
            <?php 

$MemHelper = $this->Mem();

    foreach ($paginator as $key => $resultset) {?>
                
               <li data-preview="/admin/manage_admin/detail/<?php echo $resultset->log_id?>"><a href="#"><?php echo $resultset->log_type ?></a></li>
               
            

             
         <?php  
     }  
 ?>
           
              </ul>
        </div>
        
    </div>
    <script type="text/javascript">
      
      // example how to integrate with a previewer
      var current = 0,
        $preview = $( '#preview' ),
        $carouselEl = $( '#carousel' ),
        $carouselItems = $carouselEl.children(),
        carousel = $carouselEl.elastislide( {
          current : current,
          minItems : 3,
          onClick : function( el, pos, evt ) {

            changeImage( el, pos );
            evt.preventDefault();

          },
          onReady : function() {

            changeImage( $carouselItems.eq( current ), current );
            
          }
        } );

      function changeImage( el, pos ) {
		  $('#preview').empty();
$('#preview').load(el.data( 'preview' ));
       // $preview.attr( 'src', el.data( 'preview' ) );
        $carouselItems.removeClass( 'current-img' );
        el.addClass( 'current-img' );
        carousel.setCurrent( pos );

      }

  </script>
          
      

<script type="text/javascript">
<?php if(!empty($this->messages)){?>
	jsuccess('<?php echo implode (' ',$this->messages) ?>');

<?php 	}?>
</script>