       <?php 
if(empty($row)){
	echo "no record found";return;
	}
       ?>

<div id="tab3" class="hideCls">
        <div class="span6">
          
            
           <ul id="preview" class="right scrollClass">
             
           
            </ul>
                 
            
          
        </div>
        
        <div class="clear"></div>
        <div class="row-fluid">
          <ul id="carousel" class="elastislide-list">
            <?php 

$MemHelper = $this->Mem();

    foreach ($paginator as $key => $resultset) {?>
                
               <li data-preview="/admin/manage_admin/detail/<?php echo $resultset->log_id?>"><a href="#"><p><?php echo $resultset->log_type ?></p></a></li>
               
            

             
         <?php  
     }  
 ?>
           
              </ul>
        </div>
        
    </div>
    <script type="text/javascript">
      
      // example how to integrate with a previewer
      var current = 0,
        $preview = $( '#preview' ),
        $carouselEl = $( '#carousel' ),
        $carouselItems = $carouselEl.children(),
        carousel = $carouselEl.elastislide( {
          current : current,
          minItems : 10,
          onClick : function( el, pos, evt ) {

            changeImage( el, pos );
            evt.preventDefault();

          },
          onReady : function() {

            changeImage( $carouselItems.eq( current ), current );
            
          }
        } );

      function changeImage( el, pos ) {
		  $('#preview').empty();
$('#preview').load(el.data( 'preview' ));
       // $preview.attr( 'src', el.data( 'preview' ) );
        $carouselItems.removeClass( 'current-img' );
        el.addClass( 'current-img' );
        carousel.setCurrent( pos );

      }

  </script>
          
      

<script type="text/javascript">
<?php if(!empty($this->messages)){?>
	jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');

<?php 	}?>
</script>