<?php 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);
//get an array of the route params and their values
$routeparams=$routeMatch->getParams();

?> 

<div class="tabinnercontent">
     User Name : <input type="text" name="user" value="" />User Name : <input type="text" name="user" value="" />
     User Name : <input type="text" name="user" value="" /><input type="submit" value="" />
        
    
	<div id="no-more-tables">
		<table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
			<thead class="cf">
				<tr>
					<th class="numeric">order #</th>
 					<th >username</th>
					<th>date of order</th>
					<th>transaction type</th>
					<th>pass / fail</th>
					<th>status</th>
					<th>action</th>
				</tr>
			</thead>
			<tbody>
				<?php 
                                if(isset($orderData->orders)){
				foreach ($orderData->orders as $row) {
 				 
 ?>
				<tr>
					<td data-title="order #" class="numeric"><?php echo $row ->transaction->transaction_id ?></td>
  					<td><?php echo $row ->username ?></td>
      				<td><?php echo $row ->balance->ending_balance ?></td>
            		<td><?php echo $row->transaction ->transaction_type ?></td>   
               		<td><?php echo $row->transaction ->amount ?></td>   
               		<th>pass</th>
					<td data-title="action">
						<a href="/index/account-dopayout/<?=$row->transaction->transaction_id?>" class="white" data-toggle="modal" data-target="#popup">View</a>
					</td>
				</tr>
				
                                <?php  } }?>
			</tbody>
		</table>
		<div class="clear"></div>
		<div class="blur"  style="text-align:left">
						<div class="pagination pagination-toolbar">
							 <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo ($page>1)?$page-1:1;?>">< Previous</a>
<?php 
for($i=1;$i<=$page;$i++){
  if($i==$page){
        echo " <span class='count'>$i</span> |";

  }else{
   echo "<a class='paginate_click' href='/admin/OrderHistory?page=".$i."'>$i</a> |"; 
    }
  }
?>

  <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo $page+1;?>">Next ></a>
						</div>
		</div>
	</div>
</div>