<?php 
 $sm = $this->getHelperPluginManager()->getServiceLocator();
 
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);

//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  


?>
 <a  data-toggle="modal" data-target="#popup" href="/index/admin-add" class="btn  btn-primary btn-xs" role="group" aria-label="...">Add</a><button onclick= "adminedit()" class="btn btn-xs  btn-primary" role="group" aria-label="...">Edit</button><button onclick="admindelete()" class="btn btn-xs btn-primary" role="group" aria-label="...">Del</button>


 
<div class="tabinnercontent">
								<div id="no-more-tables">
									<form class="formstyle" method="post">
									<table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
										<thead class="cf">
											<tr>
												<th>selected</th>
												<th>profile picture</th>
												<th>username</th>
												<th class="numeric">admin level</th>
												<th>admin recent transaction</th>
												<th>date added disc</th>
												<th>status</th>
											</tr>
										</thead>
										<tbody>
											<?php 
 $MemHelper = $this->Mem();
 foreach ($paginator as $key => $resultset) {
   
 ?>

   
		<tr>
		<td data-title="selected" class="numeric"> 
				<input type="radio" class="inputbox unistyle"id="radio" name="adminid" value="<?php echo $resultset->user_id ?>"></td>
			

			<td data-title="profile picture" class="numeric"><img src="images/admin-u-profile.png"></td>
			<td data-title="username"><?php echo $resultset -> username ?></td>
			<td data-title="admin level"><?php echo $resultset -> role ?></td>
			<td data-title="admin recent transaction"><a id="button" class="white " data-toggle="modal" data-target="#listpopup" href="/index/admin-tran/<?php echo $resultset -> user_id?>" >recent transactions</a></td>
			<td data-title="date added disc"><?php echo $MemHelper->showDate($resultset -> create_date)?></td>
			<td data-title="status"><?php
        echo ($resultset ->disable_account == 0)?'<img src="/img/status.png" />':
		'<img src="/img/cross.png" />'
		; 
     ?></td>
		</tr>
											<?php }?>
											
										</tbody>
									</table>
									</form>
									<div class="clear"></div>
									<div class="blur" style="text-align:left">
													<div class="pagination pagination-toolbar">
                            <?php // add at the end of the file after the table
                              echo $this->paginationControl(
                                  // the paginator object
                                  $this->paginator,
                                  // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
                                  'sliding',
                                  // the partial to use to render the control
                                  'layout/paginator.phtml'
                                  ,
                                  //the route to link to when a user clicks a control link
                                  array(            'order_by'=>$order_by,'order' => $order,'q'=>$q
                                        )
                              );
                            ?>
														    
													</div>
									</div>
								</div>
							</div>

<script type="text/javascript">
function adminedit (argument) {
  var adminid=getRadioValue ()
  if (adminid==0) {

alert('please select user');    
  }else{

     var url = "/index/adminEdit/"+adminid;

        
     $mymodal.find(".modal-content").load(url, function() { 
           $mymodal.modal(); 
    });
  
      

  }
}

function admindelete (argument) {
  var adminid=getRadioValue ('adminid');
  if (adminid==0) {

alert('please select user');    
  }else{

    
    var url = "/index/adminDeactivate/"+adminid;
      $mymodal.find(".modal-content").load(url, function() { 
           $mymodal.modal(); 
    });

  }
}

$(document)  
  .on('show.bs.modal', '.modal', function(event) {
    $(this).appendTo($('body'));
  })
  .on('shown.bs.modal', '.modal.in', function(event) {
    setModalsAndBackdropsOrder();
  })
  .on('hidden.bs.modal', '.modal', function(event) {
    setModalsAndBackdropsOrder();
  });

function setModalsAndBackdropsOrder() {  
  var modalZIndex = 1040;
  $('.modal.in').each(function(index) {
    var $modal = $(this);
    modalZIndex++;
    $modal.css('zIndex', modalZIndex);
    $modal.next('.modal-backdrop.in').addClass('hidden').css('zIndex', modalZIndex - 1);
});
  $('.modal.in:visible:last').focus().next('.modal-backdrop.in').removeClass('hidden');
}

</script> 