   <form id="adminaddfrm" action="/index/admin-add" method="post" enctype="multipart/form-data" name="addUserFrm" class="form-horizontal" role="form">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Add Admin</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="inputLogin" class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft">username</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                  	            <input id="username" name="username" type="text" class="form-control" value="" placeholder="Username">

                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="inputName" class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft">email</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                                <input  id="email" name="email_address" type="text" class="form-control" value="" placeholder="Email">

                  </div>
                </div>
              </div>
               
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="inputAdminName" class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft">account type</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                   <select name="role">
                <option value="">Select...</option>
                <option value="1">Admin</option>
                <option value="2">Member</option>
                 <option value="3">Superadmin</option>
              </select>
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label for="inputCreated" class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft">profile photo</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
 					no
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="checkdata()">save user</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">cancle</button>
          </div>
        </form>



         
           
           
            
        
<script type="text/javascript">
<?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$this->messages) ?>');
	
    <?php }else {?>
       jsuccessAndRefresh('<?php echo implode (' ',$this->messages) ?>');
    <?php }
    
    
    }?>

function checkdata()
{ 

	var getnm = trim(document.getElementById("username").value);
        var email = trim(document.getElementById("email").value);
	
	if(getnm == "" || email == "")
	{
		alert("Please fill all the value properly.");return false;
	}
        var email = document.getElementById('email');
    var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;

    if (!filter.test(email.value)) {
    alert('Please provide a valid email address');
    email.focus;
    return false;
    }
   $.post($('#adminaddfrm').attr('action'), $('#adminaddfrm').serialize(), function( data ) {
        $( "#popup" ).find(".modal-content").html( data );
});
	return true;
	
}

function trim(str) {
        return str.replace(/^\s+|\s+$/g,"");
}
function resetdata()
{
    	document.getElementById("username").value="";
        document.getElementById("email").value="";
}

</script>