<table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
		<thead class="cf">
			<tr>
				<th><a href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'username', 'order' => $url_order)));?>"></a>user</th>
				<th >plan</th>
				<th ><a href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'data_usage', 'order' => $url_order)));?>"></a>data usage (GB)</th>
				<th># of image</th>
				<th>avg. image size</th>
				<th># of video</th>
				<th>avg. video size</th>
				<th># of audio comments</th>
				<th>avg. audio comment</th>
				<th>total % used</th>
			</tr>
		</thead>
		<tbody>
			<?php 
    $MemHelper = $this->Mem();
    $userTable = $MemHelper->getUserTable();

foreach ($paginator as $key => $user) {
$userData =  $userTable->getUser($user->user_id);

?>
			<tr>
				<td data-title="user"><?php echo empty($userData)?$user->user_id:$userData -> username ?></td> 
				<td data-title="plan"><?php echo $user -> plan ?></td> 
				<td data-title="data usage (GB)"><?php echo $MemHelper->toByteString($user -> data_usage) ?></td>
				<td data-title="# of image" ><?php echo $user -> total_image ?></td>
				<td data-title="avg. image size"><?php echo $MemHelper->toByteString($user -> average_image) ?></td>
				<td data-title="# of video"><?php echo $user -> total_vedio ?></td>
				<td data-title="avg. video size"><?php echo $MemHelper->toByteString($user -> average_vedio) ?></td>
				<td data-title="# of audio comments"><?php echo $user -> total_audio ?></td>
				<td data-title="avg. audio comment"><?php echo $MemHelper->toByteString($user -> average_audio) ?></td>
				<td data-title="total % used"><?php echo $MemHelper->calPercentge($user -> data_usage,$user -> allowed_size)?> %</td>
			</tr>
			<?php  } ?>
		</tbody>
	</table>