
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Moderate Events</h4>
        </div>
        <div class="fgallery fotorama"  data-click="false" data-swipe="true" data-ratio="800/546" data-max-width="100%"  data-width="100%" data-allow-full-screen="true" data-fit="cover" data-click="true"  data-nav="thumbs">
          <?php 

$MemHelper = $this->Mem();

    foreach ($this->medias as  $media) {
                $json_array = json_decode ($media->metadata, true );
             if(isset($json_array ['S3_files'] ['type'] ['image']))  
             { 
              $mediaUrl = $MemHelper->EventPic($media->eventmeta);

 
              ?>
          <img src="<?=$mediaUrl?>">
          <?php }else{
				$mediaUrl = $MemHelper->EventPic($media->eventmeta);

          ?>
         <a data-video="true" href="/jwplayer/index.html"><img src="<?=$mediaUrl?>"></a>
        
            

          <?php  
     }  } 
 ?>
        </div>
<script type="text/javascript">
$(function () {
  $('.fotorama').fotorama();
});
</script>