
<?php if($eventStatus == 'inactive') {?>
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
<h4 class="modal-title" id="myModalLabel">Approve Event </h4>
</div>



<form  id="form1" action="/index/event-approve" class="form-horizontal formstyle" role="form" method="post">
  <input name="event_id" type="hidden" value="<?=$event->event_id?>" >

<div class="modal-body">
<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="form-group padleftright30">
        <label for="inputName" >select reason :</label>
        <div class="radioboxs">
            <div class="line">
                <input type="radio" name="reason" value="the event is significant" class="unistyle" id="il">&nbsp;the event is significant
            </div>
            <div class="line">
                <input type="radio" name="reason" value="i am available" class="unistyle" id="il">&nbsp;i am available
            </div>
            
            <div class="line">
                <input type="radio" name="reason" value="i am closed with the owner of event" class="unistyle" id="il">&nbsp;i am closed with the owner of event
            </div>
            <div class="line"> 
                <input type="radio" name="reason" id="other" value="other" class="unistyle">&nbsp;other
                 
            </div>
            <div class="line padtop10">
                 <textarea name="other_reason" id="reason_other" cols="1" rows="1" class="input-group-lg" style="width:100%;height:100px;"></textarea>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-primary" onclick="checkdata()">Approve</button>
<button type="button" class="btn btn-default" data-dismiss="modal">cancle</button>
</div>


</form>

<?php }else{?>
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
<h4 class="modal-title" id="myModalLabel">Disapprove Event</h4>
</div>



<form  id="form1" action="/index/eventDisapprove" class="form-horizontal formstyle" role="form" method="post">
  <input name="event_id" type="hidden" value="<?=$event->event_id?>" >

<div class="modal-body">
<div class="row">
<div class="col-sm-12 col-md-12 col-lg-12">
    <div class="form-group padleftright30">
        <label for="inputName" >select reason :</label>
        <div class="radioboxs">
            <div class="line">
                <input type="radio" name="reason" value="Inappropriate Language" id="il" class="unistyle">&nbsp;Inappropriate Language
            </div>
            <div class="line">
                <input type="radio" name="reason" value="sexual content" class="unistyle" id="il">&nbsp;sexual content
            </div>
            <div class="line">
                <input type="radio" name="reason" value="unauthorized material" class="unistyle" id="il">&nbsp;unauthorized material
            </div>
            <div class="line">
                <input type="radio" name="reason" id="other" value="other" class="unistyle">&nbsp;other
                 
            </div>
            <div class="line padtop10">
                 <textarea name="other_reason" id="reason_other" cols="1" rows="1" class="input-group-lg" style="width:100%;height:100px;"></textarea>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-primary" onclick="checkdata()">Disapprove</button>
<button type="button" class="btn btn-default" data-dismiss="modal">cancle</button>
</div>


</form>
<?php }?>


<script type="text/javascript">
<?php if(!empty($messages)){

if($status == 'error'){?> 
jerror('<?php echo implode (' ',$messages) ?>');

<?php  }else {?>
jsuccessAndRefresh('<?php echo implode (' ',$messages) ?>');
<?php }


}?>

function checkdata()
{ var reason = $("input[name='reason']:checked").val();
if(!reason){
alert('please select reson');
return false;

}else if(reason == 'other'){
var txt = $("#reason_other").val();

if(!txt.trim()){
alert ('please give reason ');
return false;
}

}
$.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
//show in pop up
$( "#popup" ).find(".modal-content").html( data );
});
return true;

}
doinitFrom();

</script>

