<?php 
if(empty($feedback)){
  echo "no record found<>";return;
  }
   $MemHelper = $this->Mem();
   $userTable = $MemHelper->getUserTable();
   $userData =  $userTable->getUser($feedback->user_id);


       ?>
          
<form role="form" class="form-horizontal">
          <div class="modal-header">
            <button data-dismiss="modal" class="close" type="button"><span aria-hidden="true">x</span><span class="sr-only">Close</span></button>
            <h4 id="myModalLabel" class="modal-title">View Feedback</h4>
          </div>
          <div class="modal-body">
            <div class="row">
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft" for="inputLogin">profile photo</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                    <?php echo '<img width="56px" src="'. $MemHelper->ProfilePic($userData -> metadata).'"/>'; ?>
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft" for="inputName">Name</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                    <input type="text" value="<?php echo $feedback->name?>" id="inputName" class="form-control">
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft" for="inputCreatetime">Create time</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                    <input type="text" value="<?php echo $feedback->create_time?>" id="inputCreatetime" class="form-control">
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft" for="inputAdminName">email</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                    <input type="text" value="<?php echo $feedback->email?>" id="inputAdminName" class="form-control">
                  </div>
                </div>
              </div>
              <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="form-group">
                  <label class="col-lg-3 col-md-3 col-sm-3 control-label nopadleft" for="inputCreated">feedback</label>
                  <div class="col-lg-9 col-md-9 col-sm-9 nopadleft">
                    <textarea class="form-control" rows="1" cols="1"><?php echo $feedback->message?></textarea>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
             <button data-dismiss="modal" class="btn btn-default" type="button">cancel</button>
          </div>
        </form>
       
    