<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/img/favicon.png">

    <title>Login</title>
    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" >
  <link type="text/css" rel="stylesheet" href="css/easy-responsive-tabs.css" />
  <link type="text/css" rel="stylesheet" href="css/uniform.css" />
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  
  </head>

  <body viewsource="no">
  <header>  
    <div class="row">
      <div class="col-lg-12 text-center">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <img src="images/notification.png"/>
        </button>
        <h1 id="logo">
          <a href="index.html">memreas</a>
        </h1>
      </div>
    </div>
  </header>
  <div id="contentwrap"><!-- contentwrap -->
    <div class="container padtopbot borderbottom">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
          <div class="scriptext">
            Sharing memories just got easier!
          </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6">
          <form id="form-user-login" name="user_login_frm" method="post" action="/index/login">
            <div class="login-top row">
              <div class="col-xs-5 nopadleft">
                <input type="text" onfocus="if(this.value == 'Email')this.value = '';" onblur="if(!/\S/.test(this.value))this.value=this.defaultValue" placeholder="Username" name="username" class="form-control pull-left loginw"/>
              </div>
              <div class="col-xs-7">
                <input type="password" onfocus="if(this.value == 'Password')this.value = '';" onblur="if(!/\S/.test(this.value))this.value=this.defaultValue" placeholder="Password" name="password"  class="form-control pull-left loginw">
                <input class="btn btn-sm  pull-left login-btn" type="submit" name="log in" value="log in">
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="container padtopbot2">
      <div class="row">
        <div class="biglogo text-center">
          <img src="images/admin-logo.png"/>
        </div>
      </div>
    </div>
  </div>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 footerdiv">
          &copy; 2014 memreas, llc. All rights reserved.
        </div>
      </div>
    </div>
  </footer>
  
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="js/bootstrap.js"></script>
  <script src="js/easyResponsiveTabs.js" type="text/javascript"></script>
  <script src="js/blocksit.js"></script>
  <script src="js/jquery.uniform.js"></script>
  <script>
    $(document).ready(function(){
      $('#horizontalTab').easyResponsiveTabs({
        type: 'default', //Types: default, vertical, accordion           
        width: 'auto', //auto or any width like 600px
        fit: true,   // 100% fit in a container
        closed: 'accordion', // Start closed if in accordion view
        activate: function(event) { // Callback function if tab is switched
          var $tab = $(this);
          var $info = $('#tabInfo');
          var $name = $('span', $info);
          $name.text($tab.text());
          $info.show();
        }
      });
      $uniformed = $(".formstyle").find("input.unistyle, textarea, select, a.uniformTest");
      $uniformed.uniform();
    });
  </script>
  </body>
</html>
