<?php 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);
//get an array of the route params and their values
$routeparams=$routeMatch->getParams();

?> 

<div class="tabinnercontent">
         User Name : <input id="ordHisUser" type="text" name="username" value="<?=$username?>" />
         From  : <input id="ordHisFrom" type="text" name="from" value="<?=$fromDate?>" />
         To : <input id="ordHisTo" type="text" name="to" value="<?=$toDate?>" />
         <input type="submit" value="Get History" onclick="orderHistory()" />
	<div id="no-more-tables">
		<table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
			<thead class="cf">
				<tr>
					<th >username</th>
					<th>transaction type</th>
					<th>Begining Balance</th>
					<th>amount</th>
					<th>ending Balance</th>
					<th>pass / fail</th>
										<th>currency</th>

 					<th>Transaction Date</th> 
				</tr>
			</thead>
			<tbody>
				<?php 
                                if(isset($orderData->orders)){
				foreach ($orderData->orders as $row) {
				$status = $row->transaction->pass_fail == 1?'pass':'fail';
   $transaction_response = json_decode($row->transaction->transaction_response);
$plan = isset($transaction_response->plan->name)?$transaction_response->plan->name:'';
   
 ?>
				<tr>
					<td data-title="username" ><?=$row->username?></td>
					<td data-title="transaction type"><a href="/index/orderHistoryDetail/<?=$row->transaction->transaction_id?>" class="white" data-toggle="modal" data-target="#popup"><?php echo $row ->transaction->transaction_type ?></a>
</td>
					<td data-title="order #" class="numeric"><?=$row->balance->starting_balance?></td>
					<td data-title="order #" class="numeric"><?=$row->transaction->amount?></td>
					<td data-title="order #" class="numeric"><?=$row->balance->ending_balance?></td>			
					<td data-title="pass / fail"><?=$status?></td>
					<td data-title="Currency"><?=$row->transaction->currency?></td>
					<td data-title="Transaction Date"><?php echo $row ->transaction->transaction_sent ?></td>
				</tr>
				
                                <?php  } }?>
			</tbody>
		</table>
		<div class="clear"></div>
		<div class="blur"  style="text-align:left">
						<div class="pagination pagination-toolbar">
							 <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo ($page>1)?$page-1:1;?>">< Previous</a>
<?php 
for($i=1;$i<=$page;$i++){
  if($i==$page){
        echo " <span class='count'>$i</span> |";

  }else{
   echo "<a class='paginate_click' href='/admin/OrderHistory?page=".$i."'>$i</a> |"; 
    }
  }
?>

  <a class="paginate_click" href="/index/OrderHistory?page=<?php echo $page+1;?>">Next ></a>
						</div>
		</div>
	</div>
</div>
<script>
    function orderHistory(){
        
         var obj = {};
        obj.username = $('#ordHisUser').val();
        obj.form = $('#ordHisFrom').val();
        obj.to = $('#ordHisTo').val();
        
        
        doSearchAjax(obj);
        
    }
    </script>