<?php 
$sm = $this->getHelperPluginManager()->getServiceLocator();
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);
//get an array of the route params and their values
$routeparams=$routeMatch->getParams();

?> 

<div class="tabinnercontent">
	<div id="no-more-tables">
		<table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
			<thead class="cf">
				<tr>
					<th >username</th>
					<th>transaction type</th>
					<th>Begining Balance</th>
					<th>amount</th>
					<th>ending Balance</th>
					<th>pass / fail</th>
										<th>currency</th>

 					<th>Transaction Date</th> 
				</tr>
			</thead>
			<tbody>
				<?php 
                                if(isset($orderData->orders)){
				foreach ($orderData->orders as $row) {
				
   $transaction_response = json_decode($row->transaction_response);
$plan = isset($transaction_response->plan->name)?$transaction_response->plan->name:'';
   
 ?>
				<tr>
					<td data-title="username" ><?=$row->username?></td>
					<td data-title="transaction type">						<a href="/index/orderHistoryDetail/<?=$row->transaction_id?>" class="white" data-toggle="modal" data-target="#popup"><?php echo $row ->transaction_type ?></a>
</td>
					<td data-title="order #" class="numeric"><?=$row->balance->starting_balance?></td>
					<td data-title="order #" class="numeric"><?=$row->amount?></td>
					<td data-title="order #" class="numeric"><?=$row->balance->ending_balance?></td>			
					<td data-title="pass / fail">pass</td>
										<td data-title="Currency">USD</td>

					<td data-title="Transaction Date"><?php echo $row ->transaction_sent ?></td>
				</tr>
				
                                <?php  } }?>
			</tbody>
		</table>
		<div class="clear"></div>
		<div class="blur"  style="text-align:left">
						<div class="pagination pagination-toolbar">
							 <a class="paginate_click" href="/admin/OrderHistory?page=<?php echo ($page>1)?$page-1:1;?>">< Previous</a>
<?php 
for($i=1;$i<=$page;$i++){
  if($i==$page){
        echo " <span class='count'>$i</span> |";

  }else{
   echo "<a class='paginate_click' href='/admin/OrderHistory?page=".$i."'>$i</a> |"; 
    }
  }
?>

  <a class="paginate_click" href="/index/OrderHistory?page=<?php echo $page+1;?>">Next ></a>
						</div>
		</div>
	</div>
</div>