 
           <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Payout Comment</h4>
          </div>
          <div class="modal-body">
            <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group padleftright30">
                                    <label for="inputName" >select reason :</label>
                                    <div class="radioboxs">
                                        <div class="line padtop10">
                                             <textarea name="other_reason" id="reason_other" cols="1" rows="1" class="input-group-lg" style="width:100%;height:100px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-primary" onclick="checkdata()">payout</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">cancel</button>
          </div>
       