 <?php 
 use Application\Model\user;
  $sm = $this->getHelperPluginManager()->getServiceLocator();
 
$router=$sm->get('Router');
$request=$sm->get('Request');
$routeMatch=$router->match($request);

//get an array of the route params and their values
$routeparams=$routeMatch->getParams();
  


?> 
<div class="tabinnercontent">
                <div id="no-more-tables">
                  <form class="formstyle" method="post">
                  <table class="col-md-12 table-bordered table-striped table-condensed cf nopadding">
                    <thead class="cf">
                      <tr>
                        <th class="numeric">id</th>
                        <th> <a class="paginate_click" href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'username', 'order' => $url_order)));?>">username</a></th>
                        <th><a class="paginate_click" href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'email_address', 'order' => $url_order)));?>">email</a></th>
                        <th class="numeric">profile photo</th>
                        <th><a class="paginate_click" href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'role', 'order' => $url_order)));?>">role</a></th>
                        <th><a class="paginate_click" href="<?php echo $this->url('index',$routeparams,array('query' => array('page' => $page, 'order_by' => 'disable_account', 'order' => $url_order)));?>">status</a></th>
                        <th>action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php 
foreach ($paginator as $key => $user) {
    # code..
?>
                      <tr>
                        <td data-title="id" class="numeric"><?php echo $key+1 ?></td>
                        <td data-title="username" class="numeric"><?php echo $user -> username ?></td>
                        <td data-title="email" ><?php echo $user -> email_address ?></td>
                        <td data-title="profile photo" class="numeric"><?php echo $user -> profile_photo ?></td>
                        <td data-title="role"><?php echo user::$role_name[$user -> role]  ?></td>
                        <td data-title="status">
                          <?php
        echo ($user ->disable_account == 0)?'<img src="/images/status.png" />':
    '<img src="/images/tick-icon.png"/>'
    ; 
     ?>
                          </td>
                        <td data-title="action">


<a class="white" href="/index/userView/<?php echo $user -> user_id ?>" data-toggle="modal" data-target="#popup"><img src="/images/edit-icon.png"/></a>

                         
                      </tr> 
   
   <?php  }?>
                      
                    </tbody>

                  </table>
                  </form>
                  <div class="clear"></div>
                  <div class="blur"  style="text-align:left">
                          <div class="pagination pagination-toolbar">
                           
                             <?php // add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    'layout/paginator.phtml'
    ,
    //the route to link to when a user clicks a control link
    array(                'order_by'=>$order_by,'order' => $order,'q'=>$q
          )
);
?>
                          </div>
                  </div>
                </div>
              </div>
               
   

  
   <tr><td colspan="9" align="left">
     
   </td></tr>
   </table>

  
