


                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Active user</h4>
                    </div>
                <form id="form1" action="/index/userActive"   method="post" class="form-horizontal formstyle" role="form">
                    <input type="hidden" name="id" value="<?php echo $user->user_id; ?>" />
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group padleftright30">
                                    <label for="inputName">select reason :</label>
                                    <div class="radioboxs">
                                        <div class="line">
                                                           <input class="unistyle" type="radio" name="reason" value="available" id="il">&nbsp;available
                                        </div>
                                        
                                        <div class="line">                                                
                                            <input type="radio" name="reason" id="other" value="other" class="unistyle">&nbsp;other
                                        </div>
                                         
                                        <div class="line padtop10">
                                             <textarea cols="1" rows="1" class="input-group-lg uniform" style="width:100%;height:100px;" name="reason" id="reason_other"  ></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                           
                         <button type="button" class="btn btn-primary" onclick="checkdata()">Yes</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">cancle</button>
                    </div>
                </form>
            
 
<script type="text/javascript">
    <?php if(!empty($messages)){
    
    if($status == 'error'){?> 
        jerror('<?php echo implode (' ',$messages) ?>');
    
    <?php  }else {?>
        jsuccessAndRefresh('<?php echo implode (' ',$messages) ?>');
    <?php }
    
    
    }?>
    
function checkdata()
{ var reason = $("input[name='reason']:checked").val();
    if(!reason){
        alert('please select reson');
            return false;

        }else if(reason == 'other'){
                    var txt = $("#reason_other").val();
                     
                    if(!txt.trim()){
                        alert ('please give reason ');
                          return false;
                    }
                    
                }
    $.post($('#form1').attr('action'), $('#form1').serialize(), function( data ) {
         //show in pop up
        $( "#popup" ).find(".modal-content").html( data );
});
    return true;
    
}
doinitFrom();
</script>

